### ISSUE TITLE
sendAsync() is deprecated on most web3 providers in favor of send()

### ISSUE THREAD

**Issue by cloudonshore** [Keydonix/uniswap-oracle#14]
The factories in the `uniswap-oracle-sdk-adapter` depend on a Provider that has `.sendAsync` defined. 

However I believe in both the provider injected by metamask at `window.ethereum`, and in the provider of a web3 1.0 instance instantiated with a JSON RPC endpoint, `sendAsync()` has been deprecated in favor of `send()`.

I was able to work around this with this approach: 
```
import Web3 from 'web3'
import * as OracleSdkAdapter from '@keydonix/uniswap-oracle-sdk-adapter'

// I have to override the prototype for getStorageAtFactory to work below
Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send

const web3Provider = new Web3(new Web3.providers.WebsocketProvider(ethWebsocketURL))
const getStorageAt = OracleSdkAdapter.getStorageAtFactory(web3Provider.currentProvider)
```

I would suggest defaulting to `.send()` or at least looking for it on instantiation of the factory.

**Comment by MicahZoltu** [comment]
`send` never made it into a specification.  Only `sendAsync` and `request`.  You should basically never use `send` in a dapp as it will cause you worlds of pain because there are like 3 different definitions of it floating around that are incompatible with each other.

`request` is ideal, but it isn't available everywhere yet, which is why the adapter does the normalize thing, because `sendAsync` is available everywhere and stable, but it is deprecated and has a sucky interface.

**Comment by cloudonshore** [comment]
@MicahZoltu 
I think I found the source of my issue. I've been using metamask's injected `window.ethereum` and I've been running into an issue with the storage provider. 

When I debug the error, I see that the error parameter here is set to `false`

<img width="796" alt="Screen Shot 2020-08-26 at 3 17 46 PM" src="https://user-images.githubusercontent.com/1197232/91346898-8121f200-e7af-11ea-9851-56515da99860.png">

https://github.com/Keydonix/uniswap-oracle/blob/1ea8c063ee32b246ab961dcb890351ea184a89d3/sdk-adapter/source/index.ts#L116

However, the only error states that are checked for are `null` and `undefined` 
https://github.com/Keydonix/uniswap-oracle/blob/1ea8c063ee32b246ab961dcb890351ea184a89d3/sdk-adapter/source/index.ts#L98

So even though the call is successful, it's getting stuck in an error state.

**Comment by MicahZoltu** [comment]
This is why we cannot have nice things.  The [JSON-RPC specification](https://www.jsonrpc.org/specification#response_object) *explicitly* says that setting `error` to `false` when there is no error is against spec.

> [the error] member **MUST NOT** exist if there was no error triggered during invocation.

I'm unlikely to change the library's behavior here since the specification is so abundantly clear that what is happening is erroneous, so I think throwing an error in that case is the correct behavior.

**Comment by MicahZoltu** [comment]
Out of curiosity, what library/client/provider is returning an object with `error: false` in it?

**Comment by cloudonshore** [comment]
Metamask v 8.0.8 on rinkeby, just the injected provider @MicahZoltu

**Comment by MicahZoltu** [comment]
I just tested on 8.0.6 and 8.0.9 and I get the same behavior on both against Rinkeby:
```js
window.ethereum.sendAsync({ jsonrpc: '2.0', id: 1, method: 'eth_getStorageAt', params: [ '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f', '0x0', 'latest' ]}, console.log)
// prints:
// { error: undefined, id: 1, jsonrpc: '2.0', result: 0x0000000000000000000000000000000000000000000000000000000000000000 }
```

While this is not to spec, and I will report that to them, it also shouldn't cause a problem with the library since `undefined` is handled.  Are you able to get the request payload that leads to the error while debugging?  Are you running the request through any middleware that may be adding `false` to the error field?

**Comment by MicahZoltu** [comment]
https://github.com/MetaMask/metamask-extension/issues/9319 created.
